# Generated by Django 4.1 on 2022-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length="100")),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
