# Generated by Django 4.1 on 2022-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
