# Generated by Django 4.1 on 2022-08-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_item_is_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="name",
            new_name="title",
        ),
    ]
