# Generated by Django 4.1 on 2022-09-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_rename_name_item_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to="gallery"),
        ),
    ]
