# Generated by Django 4.1 on 2022-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(max_length=215),
        ),
    ]
